clc;
clear all;
close all;
s=tf('s');
wn=-9;
y=0.1;
a1=wn*y;
b1=sqrt(wn*wn-a1*a1);
a2=-1;
b2=2;
sysfs1=s*s-2*a1*s+a1*a1+b1*b1;
sysfs2=s*s-2*a2*s+a2*a2+b2*b2;
sysk=1/(s+4)/(s+2)/(s+5)/(s+8)*(s+6);
sys=sysk;
rlocus(sys);
G=zpk(sys);
[z,p,k]=zpkdata(G,'v');
z=z';
p=p';
zs=num2str(z);
ps=num2str(p);
text=['零点为',zs,'  ','极点为',ps];
title (text);